// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRciqSEqv99adE8jNbjp-QUxPRau_LhBY',
    appId: '1:621863637081:web:YOUR_WEB_APP_ID',
    messagingSenderId: '621863637081',
    projectId: 'aikeyboard-18ed9',
    authDomain: 'aikeyboard-18ed9.firebaseapp.com',
    storageBucket: 'aikeyboard-18ed9.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRciqSEqv99adE8jNbjp-QUxPRau_LhBY',
    appId: '1:621863637081:android:51ba925da6eb7d16bd2148',
    messagingSenderId: '621863637081',
    projectId: 'aikeyboard-18ed9',
    storageBucket: 'aikeyboard-18ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRciqSEqv99adE8jNbjp-QUxPRau_LhBY',
    appId: '1:621863637081:ios:7e7e5b15e9c6cac8bd2148',
    messagingSenderId: '621863637081',
    projectId: 'aikeyboard-18ed9',
    storageBucket: 'aikeyboard-18ed9.appspot.com',
    iosBundleId: 'com.example.aiKeyboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRciqSEqv99adE8jNbjp-QUxPRau_LhBY',
    appId: '1:621863637081:ios:7e7e5b15e9c6cac8bd2148',
    messagingSenderId: '621863637081',
    projectId: 'aikeyboard-18ed9',
    storageBucket: 'aikeyboard-18ed9.appspot.com',
    iosBundleId: 'com.example.aiKeyboard',
  );
}
